stages:
  - build
  - test
  - notify

include:
  - local: 'backend/.backend-ci.yml'
  - local: 'frontend/.frontend-ci.yml'
  - template: Security/SAST.gitlab-ci.yml

   
semgrep-sast:
  stage: test
  needs:
    - build_backend
  variables:
    COMPILE: "true"   
    SAST_JAVA_VERSION: "16"
    MAVEN_REPO_PATH: "${CI_PROJECT_DIR}/.m2/repository"
  script:
    - echo "Запуск SAST-анализа с помощью Semgrep"

notify:
  stage: notify
  script:
    - echo "Сборка завершена успешно!"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  
  when: always 


